package com.roubao.autopilot.skills

object FeatureFlags {
    const val ENABLE_LEGACY_WORKFLOW_DIRECT_EXEC = false
    const val ENABLE_LEGACY_FRAGMENT_DIRECT_EXEC = false
    const val ENABLE_RECORDED_SKILL_DIRECT_EXEC = false
    const val ENABLE_FULL_AI_FALLBACK_IN_AUTO = false

    var ENABLE_FRAGMENT_LIBRARY = ENABLE_LEGACY_FRAGMENT_DIRECT_EXEC
    var ENABLE_SKILL_WORKFLOW_ASSEMBLER_DIRECT_EXEC = false
    var ENABLE_WORKFLOW_LIBRARY = ENABLE_LEGACY_WORKFLOW_DIRECT_EXEC
    var ENABLE_RECORDED_SKILL_LIBRARY = ENABLE_RECORDED_SKILL_DIRECT_EXEC
    var ALLOW_FULL_AI_FALLBACK = ENABLE_FULL_AI_FALLBACK_IN_AUTO
}
